# Generated by Django 3.1 on 2020-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='apartments',
            name='location',
            field=models.CharField(max_length=64, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
    ]
